/**
 * agents/orchestrator.ts
 *
 * Orchestrator Agent -- the central project manager and coordinator.
 *
 * Responsibilities:
 *   - Receives user requirements and generates PRDs
 *   - Breaks down work into tasks with dependency graphs
 *   - Dispatches tasks to Developer/Test/Review agents via MessageBus
 *   - Manages human intervention points
 *   - Tracks overall progress
 *   - Uses TaskExecutor for parallel task execution
 *
 * Extends AgentBase from core/agent-base.ts.
 * Communicates exclusively through MessageBus.
 */

import { randomUUID } from 'node:crypto';
import type { MessageBus, Message, MessageType } from '../core/message-bus.js';
import type { AgentBase, AgentConfig, TaskDescriptor, TaskResult, ToolDefinition, ToolContext, ToolResult } from '../core/agent-base.js';
import { AgentBase as AgentBaseClass } from '../core/agent-base.js';
import type { TaskExecutor, TaskNode, ExecutionResult } from '../core/task-executor.js';
import { TaskExecutor as TaskExecutorClass } from '../core/task-executor.js';
import type { Logger } from '../core/logger.js';
import type { LLMClient } from '../tools/llm-client.js';
import type { FileSystemTool } from '../tools/file-system.js';
import type { GitClient } from '../tools/git-client.js';
import type {
  PRDDocument,
  Task,
  TaskType,
  ProjectState,
  ProjectStatus,
  HumanInterventionRequest,
  InterventionType,
  TestResult as TypesTestResult,
} from '../types/index.js';
import { ORCHESTRATOR_SYSTEM_PROMPT } from '../prompts/system-prompts.js';

// ─── Types ───────────────────────────────────────────────────────────────────

/**
 * Configuration for the Orchestrator Agent.
 */
export interface OrchestratorConfig {
  id?: string;
  name?: string;
  systemPrompt?: string;
  maxIterations?: number;
  temperature?: number;
  maxTokens?: number;
  developerAgentId?: string;
  testerAgentId?: string;
  reviewerAgentId?: string;
  taskExecutorOptions?: {
    maxConcurrency?: number;
    maxRetries?: number;
    retryBaseDelay?: number;
    retryMaxDelay?: number;
    taskTimeout?: number;
  };
}

/**
 * Internal project state tracked by the orchestrator.
 */
interface OrchestratorProjectState {
  projectId: string;
  projectName: string;
  requirement: string;
  prd: PRDDocument | null;
  tasks: OrchestratorTask[];
  status: ProjectStatus;
  humanIntervention: HumanInterventionRequest | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Internal task representation used by the orchestrator.
 */
interface OrchestratorTask {
  id: string;
  type: TaskType;
  title: string;
  description: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'blocked';
  dependencies: string[];
  maxRetries: number;
  currentRetry: number;
  result?: TaskResult;
  error?: string;
  targetAgentId: string;
}

/**
 * Progress report generated by the orchestrator.
 */
export interface ProgressReport {
  projectId: string;
  projectName: string;
  status: ProjectStatus;
  totalTasks: number;
  completedTasks: number;
  failedTasks: number;
  pendingTasks: number;
  progressPercent: number;
  currentTask: string | null;
  humanIntervention: HumanInterventionRequest | null;
}

// ─── Orchestrator Agent ──────────────────────────────────────────────────────

export class OrchestratorAgent extends AgentBaseClass {
  private llm: LLMClient;
  private fs: FileSystemTool;
  private git: GitClient;
  private taskExecutor: TaskExecutor;
  private projectState: OrchestratorProjectState | null;
  private developerAgentId: string;
  private testerAgentId: string;
  private reviewerAgentId: string;
  private humanResponseResolvers: Map<string, (response: string) => void>;

  constructor(
    config: OrchestratorConfig,
    messageBus: MessageBus,
    llm: LLMClient,
    fs: FileSystemTool,
    git: GitClient,
    logger?: Logger,
  ) {
    const agentConfig: AgentConfig = {
      id: config.id,
      name: config.name ?? 'orchestrator',
      systemPrompt: config.systemPrompt ?? ORCHESTRATOR_SYSTEM_PROMPT,
      maxIterations: config.maxIterations ?? 30,
      temperature: config.temperature ?? 0.3,
      maxTokens: config.maxTokens ?? 16384,
    };

    super(agentConfig, messageBus, logger);

    this.llm = llm;
    this.fs = fs;
    this.git = git;
    this.projectState = null;
    this.developerAgentId = config.developerAgentId ?? 'developer';
    this.testerAgentId = config.testerAgentId ?? 'tester';
    this.reviewerAgentId = config.reviewerAgentId ?? 'reviewer';
    this.humanResponseResolvers = new Map();

    this.taskExecutor = new TaskExecutorClass(
      config.taskExecutorOptions ?? {
        maxConcurrency: 4,
        maxRetries: 3,
        retryBaseDelay: 1000,
        retryMaxDelay: 30000,
        taskTimeout: 300000,
      },
      logger,
    );
  }

  // ─── Lifecycle ──────────────────────────────────────────────────────────

  protected getSubscribedMessageTypes(): MessageType[] {
    return [
      'task_completed',
      'task_failed',
      'test_result',
      'review_result',
      'human_response',
    ];
  }

  protected async handleMessage(message: Message): Promise<void> {
    switch (message.type) {
      case 'task_completed':
        await this.handleTaskCompleted(message);
        break;
      case 'task_failed':
        await this.handleTaskFailed(message);
        break;
      case 'test_result':
        await this.handleTestResult(message);
        break;
      case 'review_result':
        await this.handleReviewResult(message);
        break;
      case 'human_response':
        this.handleHumanResponse(message);
        break;
    }
  }

  // ─── Main Entry Point ──────────────────────────────────────────────────

  /**
   * Execute a task. The orchestrator supports two primary task types:
   *   - 'manage_project': Full project lifecycle (analyze -> plan -> execute)
   *   - Other types are delegated to sub-agents
   */
  async execute(task: TaskDescriptor): Promise<TaskResult> {
    if (!this.isReady() && this.getStatus() !== 'busy') {
      return this.createFailureResult('Agent not initialized');
    }

    this.setStatus('busy');
    this.setActiveTask(task.id);
    this.addUserMessage(
      `[Task ${task.id}] ${task.type}: ${task.title}\n${task.description}`,
    );

    try {
      let result: TaskResult;

      switch (task.type) {
        case 'manage_project':
          result = await this.manageProject(task);
          break;
        case 'analyze_requirement':
          result = await this.analyzeRequirement(task);
          break;
        case 'plan_tasks':
          result = await this.planTasks(task);
          break;
        case 'execute_plan':
          result = await this.executePlan(task);
          break;
        default:
          result = await this.delegateTask(task);
          break;
      }

      this.setStatus('ready');
      this.setActiveTask(null);
      return result;
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error('Task execution failed', { taskId: task.id, error: errorMessage });
      this.setStatus('ready');
      this.setActiveTask(null);
      return this.createFailureResult(errorMessage);
    }
  }

  // ─── Project Management ────────────────────────────────────────────────

  /**
   * Full project lifecycle: analyze requirement -> plan tasks -> execute plan.
   */
  private async manageProject(task: TaskDescriptor): Promise<TaskResult> {
    const requirement = task.payload?.requirement as string | undefined;
    const projectName = task.payload?.projectName as string | undefined;

    if (!requirement) {
      return this.createFailureResult('No requirement provided in task payload');
    }

    const name = projectName ?? 'AI Generated Project';
    this.logger.info('Starting project management', { projectName: name });

    // Initialize project state
    this.projectState = {
      projectId: task.correlationId ?? randomUUID(),
      projectName: name,
      requirement,
      prd: null,
      tasks: [],
      status: 'analyzing',
      humanIntervention: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const logs: string[] = [];
    const artifacts: string[] = [];

    // Step 1: Analyze requirement and generate PRD
    this.logger.info('Step 1: Analyzing requirement');
    const prdResult = await this.analyzeRequirement({
      id: randomUUID(),
      type: 'analyze_requirement',
      title: 'Analyze requirement and generate PRD',
      description: requirement,
      payload: { requirement, projectName: name },
      correlationId: this.projectState.projectId,
    });

    if (!prdResult.success) {
      this.projectState.status = 'error';
      return this.createFailureResult(
        `Failed to analyze requirement: ${prdResult.error}`,
        prdResult.logs,
      );
    }

    logs.push(...prdResult.logs);
    artifacts.push(...prdResult.artifacts);

    // Step 2: Plan tasks
    this.logger.info('Step 2: Planning tasks');
    const planResult = await this.planTasks({
      id: randomUUID(),
      type: 'plan_tasks',
      title: 'Plan development tasks',
      description: 'Break down PRD into executable tasks',
      payload: { prd: this.projectState.prd },
      correlationId: this.projectState.projectId,
    });

    if (!planResult.success) {
      this.projectState.status = 'error';
      return this.createFailureResult(
        `Failed to plan tasks: ${planResult.error}`,
        [...logs, ...planResult.logs],
      );
    }

    logs.push(...planResult.logs);
    artifacts.push(...planResult.artifacts);

    // Step 3: Execute the plan
    this.logger.info('Step 3: Executing plan');
    const execResult = await this.executePlan({
      id: randomUUID(),
      type: 'execute_plan',
      title: 'Execute development plan',
      description: 'Execute all planned tasks',
      correlationId: this.projectState.projectId,
    });

    logs.push(...execResult.logs);
    artifacts.push(...execResult.artifacts);

    if (this.projectState) {
      this.projectState.updatedAt = new Date().toISOString();
    }

    return execResult.success
      ? this.createSuccessResult(
          {
            projectId: this.projectState?.projectId,
            projectName: name,
            prd: this.projectState?.prd,
            tasksCompleted: this.projectState?.tasks.filter(t => t.status === 'completed').length ?? 0,
            tasksTotal: this.projectState?.tasks.length ?? 0,
          },
          artifacts,
          logs,
        )
      : this.createFailureResult(execResult.error ?? 'Plan execution failed', logs);
  }

  // ─── Requirement Analysis ──────────────────────────────────────────────

  /**
   * Analyze user requirement and generate a PRD (Product Requirements Document).
   */
  private async analyzeRequirement(task: TaskDescriptor): Promise<TaskResult> {
    const requirement = (task.payload?.requirement as string) ?? task.description;
    const projectName = (task.payload?.projectName as string) ?? 'AI Generated Project';

    this.logger.info('Analyzing requirement', { projectName });

    const prompt = `Analyze the following software development requirement and extract key information.

Requirement: ${requirement}

Please provide:
1. A clear, concise title for this project
2. A detailed description of what needs to be built
3. Key features that should be implemented (list 3-7 features)
4. Suggested technology stack (frontend, backend, database if applicable)
5. Acceptance criteria in Given-When-Then format for each feature

Respond in JSON format with the following structure:
{
  "title": "string",
  "description": "string",
  "features": [{ "id": "string", "name": "string", "description": "string", "priority": "high|medium|low" }],
  "techStack": { "frontend": "string", "backend": "string", "database": "string", "other": ["string"] },
  "acceptanceCriteria": [{ "id": "string", "given": "string", "when": "string", "then": "string", "featureId": "string" }]
}`;

    const schema = {
      title: 'string',
      description: 'string',
      features: [{ id: 'string', name: 'string', description: 'string', priority: 'high|medium|low' }],
      techStack: { frontend: 'string', backend: 'string', database: 'string', other: ['string'] },
      acceptanceCriteria: [{ id: 'string', given: 'string', when: 'string', then: 'string', featureId: 'string' }],
    };

    let prd: PRDDocument;
    try {
      prd = await this.llm.completeStructured<PRDDocument>(prompt, schema);
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error('Failed to generate PRD from LLM', { error: errorMessage });
      return this.createFailureResult(`PRD generation failed: ${errorMessage}`);
    }

    // Validate PRD structure
    if (!prd.title || !prd.features || prd.features.length === 0) {
      return this.createFailureResult('Generated PRD is missing required fields (title, features)');
    }

    // Ensure acceptance criteria have feature IDs
    for (const ac of prd.acceptanceCriteria) {
      if (!ac.featureId && prd.features.length > 0) {
        ac.featureId = prd.features[0].id;
      }
    }

    // Save PRD document
    const prdContent = this.generatePRDDocument(prd);
    try {
      await this.fs.createDirectory('docs');
      await this.fs.writeFile('docs/PRD.md', prdContent);
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.warn('Failed to save PRD file', { error: errorMessage });
    }

    // Commit PRD
    try {
      await this.git.saveTaskCompletion('Create PRD', `Generated Product Requirements Document for ${prd.title}`);
    } catch (err: unknown) {
      this.logger.warn('Failed to commit PRD', { error: err instanceof Error ? err.message : String(err) });
    }

    // Update project state
    if (this.projectState) {
      this.projectState.prd = prd;
      this.projectState.status = 'planning';
      this.projectState.updatedAt = new Date().toISOString();
    }

    this.addAssistantMessage(`Generated PRD: ${prd.title} with ${prd.features.length} features`);
    this.logger.info('PRD generated', { title: prd.title, features: prd.features.length });

    return this.createSuccessResult(
      { prd, title: prd.title },
      ['docs/PRD.md'],
      [`Generated PRD: ${prd.title}`, `${prd.features.length} features identified`, `${prd.acceptanceCriteria.length} acceptance criteria defined`],
    );
  }

  // ─── Task Planning ─────────────────────────────────────────────────────

  /**
   * Break down the PRD into a task dependency graph.
   */
  private async planTasks(task: TaskDescriptor): Promise<TaskResult> {
    const prd = this.projectState?.prd ?? (task.payload?.prd as PRDDocument | undefined);

    if (!prd) {
      return this.createFailureResult('No PRD available for task planning');
    }

    this.logger.info('Planning tasks for PRD', { title: prd.title });

    const prompt = `Based on the following PRD, create a detailed development plan.

Project: ${prd.title}
Description: ${prd.description}
Features:
${prd.features.map(f => `- [${f.priority}] ${f.name}: ${f.description}`).join('\n')}
Tech Stack: ${JSON.stringify(prd.techStack)}
Acceptance Criteria:
${prd.acceptanceCriteria.map(ac => `- ${ac.id}: Given ${ac.given}, When ${ac.when}, Then ${ac.then}`).join('\n')}

Create a task list with the following structure:
1. Setup project structure (design_architecture)
2. Implement each feature (develop_feature) - one or more tasks per feature
3. Write tests for each feature (write_tests)
4. Run all tests (run_tests)
5. Review code (review_code)

Each task should have:
- id: unique identifier (e.g., "task-1", "task-2")
- type: one of "design_architecture", "develop_feature", "write_tests", "run_tests", "review_code"
- title: clear, concise title
- description: detailed description of what needs to be done
- dependencies: array of task IDs that must complete first
- maxRetries: number of retries (3 for development, 2 for testing, 1 for review)
- targetAgent: "developer", "tester", or "reviewer"

Respond in JSON format with an array of tasks.`;

    const schema = {
      tasks: [{
        id: 'string',
        type: 'string',
        title: 'string',
        description: 'string',
        dependencies: ['string'],
        maxRetries: 'number',
        targetAgent: 'string',
      }],
    };

    interface PlannedTask {
      id: string;
      type: TaskType;
      title: string;
      description: string;
      dependencies: string[];
      maxRetries: number;
      targetAgent: string;
    }

    let plannedTasks: PlannedTask[];
    try {
      const result = await this.llm.completeStructured<{ tasks: PlannedTask[] }>(prompt, schema);
      plannedTasks = result.tasks;
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error('Failed to plan tasks from LLM', { error: errorMessage });
      return this.createFailureResult(`Task planning failed: ${errorMessage}`);
    }

    if (!plannedTasks || plannedTasks.length === 0) {
      return this.createFailureResult('LLM returned empty task list');
    }

    // Convert to internal task representation
    const tasks: OrchestratorTask[] = plannedTasks.map((t, index) => ({
      id: t.id || `task-${index + 1}`,
      type: t.type as TaskType,
      title: t.title,
      description: t.description,
      status: index === 0 ? 'in_progress' : 'pending',
      dependencies: t.dependencies || [],
      maxRetries: t.maxRetries || 3,
      currentRetry: 0,
      targetAgent: this.resolveAgentId(t.targetAgent, t.type),
    }));

    // Validate dependency graph
    const taskIds = new Set(tasks.map(t => t.id));
    for (const task of tasks) {
      for (const dep of task.dependencies) {
        if (!taskIds.has(dep)) {
          this.logger.warn(`Task "${task.id}" has unknown dependency "${dep}", removing`);
          task.dependencies = task.dependencies.filter(d => d !== dep);
        }
      }
    }

    // Save task plan
    const tasksDoc = this.generateTasksDocument(tasks);
    try {
      await this.fs.writeFile('docs/TASKS.md', tasksDoc);
    } catch (err: unknown) {
      this.logger.warn('Failed to save tasks document', { error: err instanceof Error ? err.message : String(err) });
    }

    // Update project state
    if (this.projectState) {
      this.projectState.tasks = tasks;
      this.projectState.status = 'developing';
      this.projectState.updatedAt = new Date().toISOString();
    }

    this.addAssistantMessage(`Planned ${tasks.length} tasks with dependency graph`);
    this.logger.info('Tasks planned', { count: tasks.length });

    return this.createSuccessResult(
      { taskCount: tasks.length, tasks: tasks.map(t => ({ id: t.id, title: t.title, type: t.type })) },
      ['docs/TASKS.md'],
      [`Planned ${tasks.length} tasks`, `Dependencies mapped`, `Task plan saved to docs/TASKS.md`],
    );
  }

  // ─── Plan Execution ────────────────────────────────────────────────────

  /**
   * Execute the planned tasks using TaskExecutor for parallel execution.
   */
  private async executePlan(task: TaskDescriptor): Promise<TaskResult> {
    if (!this.projectState || this.projectState.tasks.length === 0) {
      return this.createFailureResult('No tasks to execute');
    }

    this.logger.info('Executing plan', { taskCount: this.projectState.tasks.length });
    this.projectState.status = 'developing';

    const logs: string[] = [`Executing ${this.projectState.tasks.length} tasks`];
    const artifacts: string[] = [];

    // Build TaskNodes for the TaskExecutor
    const taskNodes: TaskNode<TaskResult>[] = this.projectState.tasks.map(
      (orchTask) => ({
        id: orchTask.id,
        title: orchTask.title,
        dependencies: [...orchTask.dependencies],
        execute: async () => {
          return this.dispatchTaskToAgent(orchTask);
        },
        metadata: {
          type: orchTask.type,
          targetAgent: orchTask.targetAgent,
          maxRetries: orchTask.maxRetries,
        },
      }),
    );

    // Execute with dependency graph
    const executionResult = await this.taskExecutor.execute(taskNodes);

    // Process results
    for (const [taskId, taskResult] of executionResult.results) {
      const orchTask = this.projectState!.tasks.find(t => t.id === taskId);
      if (!orchTask) continue;

      switch (taskResult.status) {
        case 'completed':
          orchTask.status = 'completed';
          orchTask.result = taskResult.result;
          logs.push(`[COMPLETED] ${orchTask.title}`);
          if (taskResult.result?.artifacts) {
            artifacts.push(...taskResult.result.artifacts);
          }
          break;
        case 'failed':
          orchTask.status = 'failed';
          orchTask.error = taskResult.error;
          orchTask.currentRetry = taskResult.attempt;
          logs.push(`[FAILED] ${orchTask.title}: ${taskResult.error}`);
          break;
        case 'skipped':
          orchTask.status = 'blocked';
          orchTask.error = 'Skipped due to dependency failure';
          logs.push(`[SKIPPED] ${orchTask.title}`);
          break;
      }
    }

    // Determine overall result
    const allCompleted = executionResult.success;
    const failedCount = executionResult.failed;
    const skippedCount = executionResult.skipped;

    if (allCompleted) {
      this.projectState.status = 'completed';
      logs.push('All tasks completed successfully');

      try {
        await this.git.autoSave('Project completed - all tasks done');
      } catch (err: unknown) {
        this.logger.warn('Failed to commit completion', { error: err instanceof Error ? err.message : String(err) });
      }
    } else if (failedCount > 0) {
      // Check if we should request human intervention
      const failedTasks = this.projectState.tasks.filter(t => t.status === 'failed');
      if (failedTasks.length > 0 && failedTasks.every(t => t.currentRetry >= t.maxRetries)) {
        this.projectState.status = 'waiting_for_human';
        const intervention = await this.requestHumanIntervention(
          'error_escalation',
          `${failedCount} task(s) failed after all retries. Please review and provide guidance.`,
          {
            failedTasks: failedTasks.map(t => ({
              id: t.id,
              title: t.title,
              error: t.error,
            })),
            projectId: this.projectState.projectId,
          },
        );
        this.projectState.humanIntervention = intervention;
        logs.push(`Human intervention requested: ${intervention.message}`);
      } else {
        this.projectState.status = 'error';
        logs.push(`${failedCount} task(s) failed`);
      }
    }

    this.projectState.updatedAt = new Date().toISOString();

    this.addAssistantMessage(
      `Plan execution complete: ${executionResult.succeeded} succeeded, ${failedCount} failed, ${skippedCount} skipped`,
    );

    return allCompleted
      ? this.createSuccessResult(
          {
            succeeded: executionResult.succeeded,
            failed: failedCount,
            skipped: skippedCount,
            duration: executionResult.totalDuration,
          },
          artifacts,
          logs,
        )
      : this.createFailureResult(
          `${failedCount} task(s) failed, ${skippedCount} skipped`,
          logs,
        );
  }

  // ─── Task Dispatch ─────────────────────────────────────────────────────

  /**
   * Dispatch a single task to the appropriate agent via MessageBus.
   */
  private async dispatchTaskToAgent(orchTask: OrchestratorTask): Promise<TaskResult> {
    const taskDescriptor: TaskDescriptor = {
      id: orchTask.id,
      type: orchTask.type,
      title: orchTask.title,
      description: orchTask.description,
      payload: {
        prd: this.projectState?.prd,
        acceptanceCriteria: this.projectState?.prd?.acceptanceCriteria ?? [],
        techStack: this.projectState?.prd?.techStack,
        retryCount: orchTask.currentRetry,
        projectId: this.projectState?.projectId,
      },
      parentTaskId: this.projectState?.projectId,
      correlationId: this.projectState?.projectId,
    };

    this.logger.info('Dispatching task to agent', {
      taskId: orchTask.id,
      targetAgent: orchTask.targetAgent,
      type: orchTask.type,
    });

    try {
      const result = await this.delegateToSubAgent(
        orchTask.targetAgentId,
        taskDescriptor,
        300000, // 5 minute timeout
      );
      return result;
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error('Task dispatch failed', {
        taskId: orchTask.id,
        targetAgent: orchTask.targetAgent,
        error: errorMessage,
      });
      return this.createFailureResult(`Dispatch failed: ${errorMessage}`);
    }
  }

  /**
   * Delegate a task that is not part of the standard project lifecycle.
   */
  private async delegateTask(task: TaskDescriptor): Promise<TaskResult> {
    const targetAgent = this.resolveAgentIdFromType(task.type);
    this.logger.info('Delegating external task', {
      taskId: task.id,
      type: task.type,
      targetAgent,
    });

    return this.delegateToSubAgent(targetAgent, task, 300000);
  }

  // ─── Message Handlers ──────────────────────────────────────────────────

  /**
   * Handle task_completed messages from sub-agents.
   */
  private async handleTaskCompleted(message: Message): Promise<void> {
    const payload = message.payload as TaskResult;
    this.logger.info('Received task_completed', {
      from: message.from,
      artifacts: payload.artifacts,
    });
    this.addAssistantMessage(
      `Task completed by ${message.from}: ${payload.artifacts.length} artifacts produced`,
    );
  }

  /**
   * Handle task_failed messages from sub-agents.
   */
  private async handleTaskFailed(message: Message): Promise<void> {
    const payload = message.payload as { error?: string; taskId?: string };
    this.logger.warn('Received task_failed', {
      from: message.from,
      error: payload.error,
    });
    this.addAssistantMessage(
      `Task failed from ${message.from}: ${payload.error ?? 'unknown error'}`,
    );
  }

  /**
   * Handle test_result messages from the Tester Agent.
   * If tests fail, dispatch a fix_bug task to the Developer.
   */
  private async handleTestResult(message: Message): Promise<void> {
    const testResult = message.payload as TypesTestResult;
    this.logger.info('Received test_result', {
      from: message.from,
      passed: testResult.passedTests,
      failed: testResult.failedTests,
      total: testResult.totalTests,
    });

    if (!testResult.success && testResult.failures.length > 0 && this.projectState) {
      this.logger.info('Tests failed, dispatching fix_bug task to developer');

      const fixTask: TaskDescriptor = {
        id: `fix-${randomUUID()}`,
        type: 'fix_bug',
        title: `Fix failing tests (${testResult.failures.length} failures)`,
        description: `Fix the following test failures:\n${testResult.failures.map(f => `- ${f.testName}: ${f.error}`).join('\n')}`,
        payload: {
          testResult,
          failures: testResult.failures,
          projectId: this.projectState.projectId,
        },
        correlationId: this.projectState.projectId,
      };

      this.publish('task_assigned', this.developerAgentId, fixTask, this.projectState.projectId);
    }
  }

  /**
   * Handle review_result messages from the Reviewer Agent.
   * If review requests changes, dispatch fix tasks to the Developer.
   */
  private async handleReviewResult(message: Message): Promise<void> {
    const reviewReport = message.payload as {
      approved: boolean;
      issues: Array<{ severity: string; description: string; suggestion: string; file: string }>;
      summary: string;
    };

    this.logger.info('Received review_result', {
      from: message.from,
      approved: reviewReport.approved,
      issueCount: reviewReport.issues?.length ?? 0,
    });

    if (!reviewReport.approved && reviewReport.issues && reviewReport.issues.length > 0 && this.projectState) {
      const majorIssues = reviewReport.issues.filter(
        i => i.severity === 'critical' || i.severity === 'major',
      );

      if (majorIssues.length > 0) {
        this.logger.info('Review requested changes, dispatching fix task');
        const fixTask: TaskDescriptor = {
          id: `review-fix-${randomUUID()}`,
          type: 'fix_bug',
          title: `Address code review feedback (${majorIssues.length} issues)`,
          description: `Fix the following code review issues:\n${majorIssues.map(i => `- [${i.severity}] ${i.file}: ${i.description}\n  Suggestion: ${i.suggestion}`).join('\n')}`,
          payload: {
            reviewIssues: majorIssues,
            projectId: this.projectState.projectId,
          },
          correlationId: this.projectState.projectId,
        };

        this.publish('task_assigned', this.developerAgentId, fixTask, this.projectState.projectId);
      }
    }
  }

  /**
   * Handle human_response messages.
   */
  private handleHumanResponse(message: Message): Promise<void> {
    const payload = message.payload as { response: string; interventionId: string };
    this.logger.info('Received human_response', { interventionId: payload.interventionId });

    const resolver = this.humanResponseResolvers.get(payload.interventionId);
    if (resolver) {
      resolver(payload.response);
      this.humanResponseResolvers.delete(payload.interventionId);
    }

    if (this.projectState?.humanIntervention) {
      this.projectState.humanIntervention.response = payload.response;
      this.projectState.humanIntervention.respondedAt = new Date();
      this.projectState.status = 'developing';
      this.projectState.updatedAt = new Date().toISOString();
    }

    return Promise.resolve();
  }

  // ─── Human Intervention ────────────────────────────────────────────────

  /**
   * Request human intervention by publishing a human_request message
   * and waiting for a human_response.
   */
  private async requestHumanIntervention(
    type: InterventionType,
    message: string,
    context: Record<string, unknown>,
  ): Promise<HumanInterventionRequest> {
    const interventionId = randomUUID();
    const intervention: HumanInterventionRequest = {
      id: interventionId,
      type,
      message,
      context,
      requestedAt: new Date(),
    };

    this.logger.info('Requesting human intervention', { type, message });

    // Publish the request
    this.publish('human_request', '*', intervention, interventionId);

    // Wait for response (with timeout)
    const response = await new Promise<string>((resolve) => {
      this.humanResponseResolvers.set(interventionId, resolve);

      // Timeout after 30 minutes
      setTimeout(() => {
        const resolver = this.humanResponseResolvers.get(interventionId);
        if (resolver) {
          resolver('TIMEOUT: No human response received within 30 minutes. Continuing with best-effort approach.');
          this.humanResponseResolvers.delete(interventionId);
        }
      }, 30 * 60 * 1000);
    });

    intervention.response = response;
    intervention.respondedAt = new Date();

    return intervention;
  }

  // ─── Progress Tracking ─────────────────────────────────────────────────

  /**
   * Get a progress report for the current project.
   */
  getProgressReport(): ProgressReport | null {
    if (!this.projectState) return null;

    const tasks = this.projectState.tasks;
    const completed = tasks.filter(t => t.status === 'completed').length;
    const failed = tasks.filter(t => t.status === 'failed').length;
    const pending = tasks.filter(t => t.status === 'pending' || t.status === 'in_progress').length;
    const total = tasks.length;
    const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
    const currentTask = tasks.find(t => t.status === 'in_progress');

    return {
      projectId: this.projectState.projectId,
      projectName: this.projectState.projectName,
      status: this.projectState.status,
      totalTasks: total,
      completedTasks: completed,
      failedTasks: failed,
      pendingTasks: pending,
      progressPercent: percent,
      currentTask: currentTask?.title ?? null,
      humanIntervention: this.projectState.humanIntervention,
    };
  }

  /**
   * Get a human-readable status report.
   */
  getStatusReport(): string {
    const report = this.getProgressReport();
    if (!report) return 'No active project';

    const lines = [
      `Project: ${report.projectName}`,
      `Status: ${report.status}`,
      `Progress: ${report.completedTasks}/${report.totalTasks} tasks (${report.progressPercent}%)`,
      `Completed: ${report.completedTasks} | Failed: ${report.failedTasks} | Pending: ${report.pendingTasks}`,
    ];

    if (report.currentTask) {
      lines.push(`Current Task: ${report.currentTask}`);
    }

    if (report.humanIntervention) {
      lines.push(`Waiting for human: ${report.humanIntervention.message}`);
    }

    return lines.join('\n');
  }

  // ─── Helpers ───────────────────────────────────────────────────────────

  /**
   * Resolve the target agent ID based on the task type and LLM suggestion.
   */
  private resolveAgentId(suggestedAgent: string | undefined, taskType: string): string {
    if (suggestedAgent) {
      const agentMap: Record<string, string> = {
        developer: this.developerAgentId,
        tester: this.testerAgentId,
        reviewer: this.reviewerAgentId,
      };
      return agentMap[suggestedAgent] ?? this.resolveAgentIdFromType(taskType);
    }
    return this.resolveAgentIdFromType(taskType);
  }

  /**
   * Resolve agent ID from task type.
   */
  private resolveAgentIdFromType(taskType: string): string {
    switch (taskType) {
      case 'develop_feature':
      case 'design_architecture':
      case 'fix_bug':
        return this.developerAgentId;
      case 'write_tests':
      case 'run_tests':
        return this.testerAgentId;
      case 'review_code':
        return this.reviewerAgentId;
      default:
        return this.developerAgentId;
    }
  }

  /**
   * Generate a PRD markdown document.
   */
  private generatePRDDocument(prd: PRDDocument): string {
    const lines: string[] = [
      `# ${prd.title}`,
      '',
      '## Description',
      prd.description,
      '',
      '## Features',
      ...prd.features.map(f => `- **${f.name}** (${f.priority}): ${f.description}`),
      '',
      '## Tech Stack',
      `- Frontend: ${prd.techStack.frontend || 'N/A'}`,
      `- Backend: ${prd.techStack.backend || 'N/A'}`,
      `- Database: ${prd.techStack.database || 'N/A'}`,
      prd.techStack.other?.length ? `- Other: ${prd.techStack.other.join(', ')}` : '',
      '',
      '## Acceptance Criteria',
      ...prd.acceptanceCriteria.flatMap(ac => [
        `### ${ac.id}`,
        `- **Given**: ${ac.given}`,
        `- **When**: ${ac.when}`,
        `- **Then**: ${ac.then}`,
        '',
      ]),
    ];

    return lines.join('\n');
  }

  /**
   * Generate a tasks markdown document.
   */
  private generateTasksDocument(tasks: OrchestratorTask[]): string {
    const lines: string[] = [
      '# Development Tasks',
      '',
      `Total: ${tasks.length} tasks`,
      '',
      ...tasks.flatMap((t, i) => [
        `## ${i + 1}. ${t.title}`,
        `- ID: ${t.id}`,
        `- Type: ${t.type}`,
        `- Status: ${t.status}`,
        `- Target Agent: ${t.targetAgentId}`,
        `- Description: ${t.description}`,
        t.dependencies.length > 0 ? `- Dependencies: ${t.dependencies.join(', ')}` : '',
        `- Max Retries: ${t.maxRetries}`,
        '',
      ]),
    ];

    return lines.join('\n');
  }
}
