/**
 * agents/tester.ts
 *
 * Tester Agent -- the quality assurance specialist.
 *
 * Responsibilities:
 *   - Receives test requests via MessageBus
 *   - Generates unit tests based on code and requirements
 *   - Runs tests in sandbox
 *   - Generates E2E tests using Playwright (if frontend project)
 *   - Validates against acceptance criteria from PRD
 *   - Reports structured test results via MessageBus
 *   - Provides actionable feedback when tests fail
 *
 * Extends AgentBase from core/agent-base.ts.
 * Test results are always structured objects (never plain strings).
 */

import { randomUUID } from 'node:crypto';
import type { MessageBus, Message, MessageType } from '../core/message-bus.js';
import type { AgentConfig, TaskDescriptor, TaskResult } from '../core/agent-base.js';
import { AgentBase } from '../core/agent-base.js';
import type { Logger } from '../core/logger.js';
import type { LLMClient } from '../tools/llm-client.js';
import type { FileSystemTool } from '../tools/file-system.js';
import type { Sandbox } from '../tools/sandbox.js';
import type {
  TestResult as TypesTestResult,
  TestFailure,
  AcceptanceCriterion,
  PRDDocument,
} from '../types/index.js';
import { TESTER_SYSTEM_PROMPT } from '../prompts/system-prompts.js';

// ─── Types ───────────────────────────────────────────────────────────────────

/**
 * Configuration for the Tester Agent.
 */
export interface TesterConfig {
  id?: string;
  name?: string;
  systemPrompt?: string;
  maxIterations?: number;
  temperature?: number;
  maxTokens?: number;
  testFramework?: string;
  coverageThreshold?: number;
}

/**
 * Structured test result produced by this agent.
 * This is the canonical format -- always use this, never plain strings.
 */
export interface StructuredTestResult {
  success: boolean;
  type: 'unit' | 'e2e' | 'integration';
  totalTests: number;
  passedTests: number;
  failedTests: number;
  duration: number;
  logs: string;
  failures: TestFailure[];
}

/**
 * A single test file generated by the agent.
 */
interface GeneratedTestFile {
  path: string;
  content: string;
  description: string;
}

// ─── Tester Agent ────────────────────────────────────────────────────────────

export class TesterAgent extends AgentBase {
  private llm: LLMClient;
  private fs: FileSystemTool;
  private sandbox: Sandbox;
  private testFramework: string;
  private coverageThreshold: number;

  constructor(
    config: TesterConfig,
    messageBus: MessageBus,
    llm: LLMClient,
    fs: FileSystemTool,
    sandbox: Sandbox,
    logger?: Logger,
  ) {
    const agentConfig: AgentConfig = {
      id: config.id,
      name: config.name ?? 'tester',
      systemPrompt: config.systemPrompt ?? TESTER_SYSTEM_PROMPT,
      maxIterations: config.maxIterations ?? 20,
      temperature: config.temperature ?? 0.3,
      maxTokens: config.maxTokens ?? 16384,
    };

    super(agentConfig, messageBus, logger);

    this.llm = llm;
    this.fs = fs;
    this.sandbox = sandbox;
    this.testFramework = config.testFramework ?? 'vitest';
    this.coverageThreshold = config.coverageThreshold ?? 80;
  }

  // ─── Lifecycle ──────────────────────────────────────────────────────────

  protected getSubscribedMessageTypes(): MessageType[] {
    return ['task_assigned'];
  }

  protected async handleMessage(message: Message): Promise<void> {
    if (message.type === 'task_assigned' && message.to === this.id) {
      await this.handleTaskAssignment(message);
    }
  }

  // ─── Main Entry Point ──────────────────────────────────────────────────

  /**
   * Execute a testing task. Routes to the appropriate handler based on task type.
   */
  async execute(task: TaskDescriptor): Promise<TaskResult> {
    if (!this.isReady() && this.getStatus() !== 'busy') {
      return this.createFailureResult('Agent not initialized');
    }

    this.setStatus('busy');
    this.setActiveTask(task.id);

    // Clear history for independent context window
    this.clearHistory();

    this.addUserMessage(
      `[Task ${task.id}] ${task.type}: ${task.title}\n${task.description}`,
    );

    try {
      let result: TaskResult;

      switch (task.type) {
        case 'write_tests':
          result = await this.writeTests(task);
          break;
        case 'run_tests':
          result = await this.runTests(task);
          break;
        default:
          result = await this.runTests(task);
          break;
      }

      this.setStatus('ready');
      this.setActiveTask(null);
      return result;
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error('Task execution failed', { taskId: task.id, error: errorMessage });
      this.setStatus('ready');
      this.setActiveTask(null);
      return this.createFailureResult(errorMessage);
    }
  }

  // ─── Task Assignment Handler ───────────────────────────────────────────

  /**
   * Handle incoming task_assigned messages from the MessageBus.
   * Executes the task and responds with task_completed or task_failed.
   */
  private async handleTaskAssignment(message: Message): Promise<void> {
    const task = message.payload as TaskDescriptor;
    this.logger.info('Received test task assignment', {
      taskId: task.id,
      type: task.type,
      title: task.title,
    });

    const result = await this.execute(task);

    if (result.success) {
      this.respond(message, 'task_completed', result);
    } else {
      this.respond(message, 'task_failed', {
        error: result.error,
        taskId: task.id,
      });
    }
  }

  // ─── Test Writing ──────────────────────────────────────────────────────

  /**
   * Generate and write test files based on source code and requirements.
   */
  private async writeTests(task: TaskDescriptor): Promise<TaskResult> {
    this.logger.info('Writing tests', { title: task.title });

    const payload = task.payload ?? {};
    const targetFiles = payload.targetFiles as string[] | undefined;

    // Step 1: Identify source files to test
    const sourceFiles = await this.identifySourceFiles(targetFiles);
    if (sourceFiles.length === 0) {
      return this.createFailureResult('No source files found to test');
    }

    // Step 2: Read acceptance criteria
    const acceptanceCriteria = await this.loadAcceptanceCriteria(payload);

    // Step 3: Generate tests for each file
    const allTestFiles: GeneratedTestFile[] = [];
    const logs: string[] = [];

    for (const filePath of sourceFiles) {
      try {
        const content = await this.fs.readFile(filePath);
        const testFiles = await this.generateTestsForFile(filePath, content, acceptanceCriteria);
        allTestFiles.push(...testFiles);
        logs.push(`Generated ${testFiles.length} test file(s) for ${filePath}`);
      } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        logs.push(`Failed to generate tests for ${filePath}: ${errorMessage}`);
        this.logger.warn('Test generation failed for file', { file: filePath, error: errorMessage });
      }
    }

    if (allTestFiles.length === 0) {
      return this.createFailureResult('Failed to generate any test files', logs);
    }

    // Step 4: Write test files to disk
    const writtenFiles: string[] = [];
    for (const testFile of allTestFiles) {
      try {
        await this.fs.writeFile(testFile.path, testFile.content);
        writtenFiles.push(testFile.path);
      } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        logs.push(`Failed to write test file ${testFile.path}: ${errorMessage}`);
        this.logger.warn('Failed to write test file', { path: testFile.path, error: errorMessage });
      }
    }

    // Step 5: Run the generated tests
    const testResult = await this.executeTestsInSandbox();

    // Step 6: Publish structured test result via MessageBus
    this.publishTestResult(testResult);

    this.addAssistantMessage(
      `Tests written: ${writtenFiles.length} files. Results: ${testResult.passedTests}/${testResult.totalTests} passed.`,
    );

    return this.createSuccessResult(
      {
        testFilesCreated: writtenFiles,
        testResult,
      },
      writtenFiles,
      [
        ...logs,
        `Test results: ${testResult.passedTests}/${testResult.totalTests} passed`,
        testResult.failedTests > 0
          ? `${testResult.failedTests} test(s) failed`
          : 'All tests passed',
      ],
    );
  }

  // ─── Test Running ──────────────────────────────────────────────────────

  /**
   * Run existing tests in the sandbox and report structured results.
   */
  private async runTests(task: TaskDescriptor): Promise<TaskResult> {
    this.logger.info('Running tests', { title: task.title });

    const logs: string[] = [];
    const allResults: StructuredTestResult[] = [];

    // Step 1: Run unit tests
    this.logger.info('Running unit tests');
    const unitResult = await this.executeTestsInSandbox();
    allResults.push(unitResult);
    logs.push(`Unit tests: ${unitResult.passedTests}/${unitResult.totalTests} passed (${unitResult.duration}ms)`);

    // Step 2: Run E2E tests if frontend project
    const isFrontend = await this.detectFrontendProject();
    if (isFrontend) {
      this.logger.info('Frontend project detected, running E2E tests');
      const e2eResult = await this.runE2ETests(task);
      allResults.push(e2eResult);
      logs.push(`E2E tests: ${e2eResult.passedTests}/${e2eResult.totalTests} passed (${e2eResult.duration}ms)`);
    }

    // Step 3: Aggregate results
    const totalTests = allResults.reduce((sum, r) => sum + r.totalTests, 0);
    const totalPassed = allResults.reduce((sum, r) => sum + r.passedTests, 0);
    const totalFailed = allResults.reduce((sum, r) => sum + r.failedTests, 0);
    const allPassed = allResults.every(r => r.success);
    const totalDuration = allResults.reduce((sum, r) => sum + r.duration, 0);
    const allFailures = allResults.flatMap(r => r.failures);
    const allLogs = allResults.map(r => r.logs).join('\n\n');

    const aggregatedResult: StructuredTestResult = {
      success: allPassed,
      type: 'integration',
      totalTests,
      passedTests: totalPassed,
      failedTests: totalFailed,
      duration: totalDuration,
      logs: allLogs,
      failures: allFailures,
    };

    // Step 4: Publish structured test result
    this.publishTestResult(aggregatedResult);

    this.addAssistantMessage(
      `Tests executed: ${totalPassed}/${totalTests} passed. ${totalFailed > 0 ? `${totalFailed} failed.` : 'All passed.'}`,
    );

    return allPassed
      ? this.createSuccessResult(
          {
            unitTests: allResults.find(r => r.type === 'unit'),
            e2eTests: allResults.find(r => r.type === 'e2e'),
            summary: { total: totalTests, passed: totalPassed, failed: totalFailed },
          },
          [],
          [...logs, allPassed ? 'All tests passed' : `${totalFailed} test(s) failed`],
        )
      : this.createFailureResult(
          `${totalFailed} test(s) failed out of ${totalTests}`,
          logs,
        );
  }

  // ─── Test Generation ───────────────────────────────────────────────────

  /**
   * Generate test files for a single source file.
   */
  private async generateTestsForFile(
    filePath: string,
    codeContent: string,
    acceptanceCriteria: AcceptanceCriterion[],
  ): Promise<GeneratedTestFile[]> {
    const relevantCriteria = acceptanceCriteria.filter(ac =>
      ac.featureId && filePath.toLowerCase().includes(ac.featureId.toLowerCase().replace('feat-', '')),
    );

    const criteriaText = relevantCriteria.length > 0
      ? relevantCriteria.map(ac => `- Given ${ac.given}, When ${ac.when}, Then ${ac.then}`).join('\n')
      : 'No specific acceptance criteria for this file';

    const prompt = `Generate comprehensive tests for the following code file.

## File: ${filePath}
\`\`\`
${codeContent}
\`\`\`

## Acceptance Criteria
${criteriaText}

## Requirements
1. Use ${this.testFramework} testing framework
2. Test all exported functions, classes, and components
3. Include happy path tests
4. Include edge case tests (null, undefined, empty, boundary values)
5. Include error handling tests
6. Mock external dependencies (API calls, file system, database)
7. Use descriptive test names: "should [behavior] when [condition]"
8. Follow Arrange-Act-Assert pattern
9. Keep each test focused on one assertion
10. Use beforeEach/afterEach for setup/teardown

Respond in JSON format:
{
  "testFiles": [{
    "path": "test file path",
    "content": "complete test file content",
    "description": "what is being tested"
  }]
}`;

    const schema = {
      testFiles: [{
        path: 'string',
        content: 'string',
        description: 'string',
      }],
    };

    try {
      const result = await this.llm.completeStructured<{ testFiles: GeneratedTestFile[] }>(prompt, schema);
      return result.testFiles;
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.warn('Structured test generation failed, falling back to simple generation', { error: errorMessage });

      // Fallback: simple code generation
      const fallbackPrompt = `Write ${this.testFramework} tests for this file: ${filePath}\n\n${codeContent}\n\nProvide the complete test file content.`;
      try {
        const response = await this.llm.generateCode(fallbackPrompt);
        const testPath = filePath.replace(/\.(ts|js|tsx|jsx)$/, '.test.$1');
        return [{
          path: testPath,
          content: response,
          description: `Tests for ${filePath}`,
        }];
      } catch {
        return [];
      }
    }
  }

  // ─── Test Execution ────────────────────────────────────────────────────

  /**
   * Execute tests in the sandbox environment and return structured results.
   */
  private async executeTestsInSandbox(): Promise<StructuredTestResult> {
    const startTime = Date.now();

    // Check if there are tests to run
    const hasPackageJson = await this.fs.exists('package.json').catch(() => false);
    if (!hasPackageJson) {
      return {
        success: true,
        type: 'unit',
        totalTests: 0,
        passedTests: 0,
        failedTests: 0,
        duration: 0,
        logs: 'No package.json found -- no tests to run',
        failures: [],
      };
    }

    // Determine test command based on framework
    const testCommand = this.resolveTestCommand();

    // Run tests in sandbox
    let sandboxResult;
    try {
      sandboxResult = await this.sandbox.runTests(testCommand);
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error('Sandbox test execution failed', { error: errorMessage });
      return {
        success: false,
        type: 'unit',
        totalTests: 0,
        passedTests: 0,
        failedTests: 0,
        duration: Date.now() - startTime,
        logs: `Sandbox execution failed: ${errorMessage}`,
        failures: [{
          testName: 'sandbox-execution',
          error: errorMessage,
        }],
      };
    }

    const output = (sandboxResult.stdout ?? '') + (sandboxResult.stderr ?? '');
    const duration = Date.now() - startTime;

    // Parse test output
    const parsed = this.parseTestOutput(output);

    // Extract detailed failure information
    const failures = this.extractFailureDetails(output);

    return {
      success: parsed.failed === 0,
      type: 'unit',
      totalTests: parsed.total,
      passedTests: parsed.passed,
      failedTests: parsed.failed,
      duration,
      logs: output,
      failures,
    };
  }

  /**
   * Run E2E tests for frontend projects.
   */
  private async runE2ETests(task: TaskDescriptor): Promise<StructuredTestResult> {
    const startTime = Date.now();
    const logs: string[] = [];

    // Generate E2E test cases from acceptance criteria
    const acceptanceCriteria = await this.loadAcceptanceCriteria(task.payload ?? {});

    if (acceptanceCriteria.length === 0) {
      logs.push('No acceptance criteria found, generating basic E2E tests');
    }

    const e2eTestContent = await this.generateE2ETestContent(acceptanceCriteria);

    // Write E2E test file
    const e2eDir = 'e2e';
    try {
      await this.fs.createDirectory(e2eDir);
      await this.fs.writeFile(`${e2eDir}/app.spec.ts`, e2eTestContent);
      logs.push('E2E test file written');
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      logs.push(`Failed to write E2E test file: ${errorMessage}`);
      return {
        success: false,
        type: 'e2e',
        totalTests: 0,
        passedTests: 0,
        failedTests: 0,
        duration: Date.now() - startTime,
        logs: logs.join('\n'),
        failures: [{
          testName: 'e2e-setup',
          error: `Failed to write E2E tests: ${errorMessage}`,
        }],
      };
    }

    // Start dev server and run tests
    let server;
    try {
      server = await this.sandbox.startDevServer(3000);
      logs.push('Dev server started');
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      logs.push(`Failed to start dev server: ${errorMessage}`);
      return {
        success: false,
        type: 'e2e',
        totalTests: 0,
        passedTests: 0,
        failedTests: 0,
        duration: Date.now() - startTime,
        logs: logs.join('\n'),
        failures: [{
          testName: 'e2e-server',
          error: `Failed to start dev server: ${errorMessage}`,
          suggestion: 'Ensure the project has a "dev" script in package.json and all dependencies are installed',
        }],
      };
    }

    try {
      // Wait for server to stabilize
      await this.sleep(2000);

      // Run E2E tests
      const e2eResult = await this.sandbox.executeNpx(['playwright', 'test', '--reporter=list']);
      const output = (e2eResult.stdout ?? '') + (e2eResult.stderr ?? '');

      const parsed = this.parseTestOutput(output);
      const failures = this.extractFailureDetails(output);

      return {
        success: parsed.failed === 0,
        type: 'e2e',
        totalTests: parsed.total,
        passedTests: parsed.passed,
        failedTests: parsed.failed,
        duration: Date.now() - startTime,
        logs: output,
        failures,
      };
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      logs.push(`E2E test execution error: ${errorMessage}`);
      return {
        success: false,
        type: 'e2e',
        totalTests: 0,
        passedTests: 0,
        failedTests: 0,
        duration: Date.now() - startTime,
        logs: logs.join('\n'),
        failures: [{
          testName: 'e2e-execution',
          error: errorMessage,
          suggestion: 'Ensure Playwright is installed: npx playwright install',
        }],
      };
    } finally {
      try {
        await server.stop();
        logs.push('Dev server stopped');
      } catch {
        // Server stop failure is non-critical
      }
    }
  }

  // ─── E2E Test Generation ───────────────────────────────────────────────

  /**
   * Generate E2E test content from acceptance criteria.
   */
  private async generateE2ETestContent(criteria: AcceptanceCriterion[]): Promise<string> {
    if (criteria.length === 0) {
      return this.generateBasicE2ETest();
    }

    const prompt = `Generate Playwright E2E tests based on these acceptance criteria:

${criteria.map(ac => `- [${ac.id}] Given ${ac.given}, When ${ac.when}, Then ${ac.then}`).join('\n')}

Requirements:
1. Use @playwright/test
2. Base URL: http://localhost:3000
3. Each test should be independent
4. Use data-testid selectors where possible
5. Include proper waits and assertions
6. Handle loading states

Provide the complete test file content as a string.`;

    try {
      return await this.llm.generateCode(prompt);
    } catch {
      return this.generateBasicE2ETest();
    }
  }

  /**
   * Generate a basic E2E smoke test.
   */
  private generateBasicE2ETest(): string {
    return `import { test, expect } from '@playwright/test';

test('basic page load', async ({ page }) => {
  await page.goto('http://localhost:3000');
  await expect(page).toHaveTitle(/.+/);
  const body = await page.locator('body');
  await expect(body).toBeVisible();
});

test('no console errors', async ({ page }) => {
  const errors: string[] = [];
  page.on('console', (msg) => {
    if (msg.type() === 'error') {
      errors.push(msg.text());
    }
  });
  await page.goto('http://localhost:3000');
  expect(errors).toHaveLength(0);
});`;
  }

  // ─── Source File Discovery ──────────────────────────────────────────────

  /**
   * Identify source files to test.
   */
  private async identifySourceFiles(targetFiles?: string[]): Promise<string[]> {
    if (targetFiles && targetFiles.length > 0) {
      return targetFiles.filter(f => !f.includes('.test.') && !f.includes('.spec.'));
    }

    try {
      const allFiles = await this.fs.listAllFiles();
      return allFiles.filter(f => {
        const isCodeFile = /\.(ts|js|tsx|jsx)$/.test(f);
        const isNotTest = !f.includes('.test.') && !f.includes('.spec.');
        const isNotConfig = !f.includes('node_modules') &&
          !f.includes('dist/') &&
          !f.includes('build/') &&
          !f.includes('.config.') &&
          f !== 'package.json' &&
          f !== 'tsconfig.json';
        return isCodeFile && isNotTest && isNotConfig;
      });
    } catch {
      return [];
    }
  }

  // ─── Acceptance Criteria Loading ────────────────────────────────────────

  /**
   * Load acceptance criteria from PRD or task payload.
   */
  private async loadAcceptanceCriteria(payload: Record<string, unknown>): Promise<AcceptanceCriterion[]> {
    // Try from payload first
    const payloadAC = payload.acceptanceCriteria as AcceptanceCriterion[] | undefined;
    if (payloadAC && payloadAC.length > 0) {
      return payloadAC;
    }

    // Try from PRD file
    try {
      const prdContent = await this.fs.readFile('docs/PRD.md');
      return this.extractAcceptanceCriteria(prdContent);
    } catch {
      return [];
    }
  }

  /**
   * Extract acceptance criteria from PRD markdown.
   */
  private extractAcceptanceCriteria(prdContent: string): AcceptanceCriterion[] {
    const criteria: AcceptanceCriterion[] = [];
    const regex = /###\s*(\S+)\s*\n-?\s*\*\*Given\*\*:\s*([^\n]+)\n-?\s*\*\*When\*\*:\s*([^\n]+)\n-?\s*\*\*Then\*\*:\s*([^\n]+)/g;

    let match;
    while ((match = regex.exec(prdContent)) !== null) {
      criteria.push({
        id: match[1].trim(),
        given: match[2].trim(),
        when: match[3].trim(),
        then: match[4].trim(),
        featureId: '',
      });
    }

    return criteria;
  }

  // ─── Test Output Parsing ───────────────────────────────────────────────

  /**
   * Parse test output to extract pass/fail counts.
   */
  private parseTestOutput(output: string): { passed: number; failed: number; total: number } {
    // Try multiple patterns for different test frameworks

    // Vitest / Jest pattern: "Tests  X passed (Y)"
    const vitestMatch = output.match(/Tests\s+(\d+)\s+passed/i);
    const vitestFailed = output.match(/(\d+)\s+failed/i);

    // Jest pattern: "X passed, Y failed"
    const jestMatch = output.match(/(\d+)\s+pass(?:ing|ed)/i);
    const jestFailedMatch = output.match(/(\d+)\s+fail(?:ing|ed)/i);

    // Generic pattern: "X passing, Y failing"
    const genericPassed = output.match(/(\d+)\s+pass(?:ing|ed)/i);
    const genericFailed = output.match(/(\d+)\s+fail(?:ing|ed)/i);

    // Playwright pattern
    const pwMatch = output.match(/(\d+)\s+passed/i);
    const pwFailed = output.match(/(\d+)\s+failed/i);

    let passed = 0;
    let failed = 0;

    if (vitestMatch) {
      passed = parseInt(vitestMatch[1], 10);
      failed = vitestFailed ? parseInt(vitestFailed[1], 10) : 0;
    } else if (jestMatch) {
      passed = parseInt(jestMatch[1], 10);
      failed = jestFailedMatch ? parseInt(jestFailedMatch[1], 10) : 0;
    } else if (genericPassed) {
      passed = parseInt(genericPassed[1], 10);
      failed = genericFailed ? parseInt(genericFailed[1], 10) : 0;
    } else if (pwMatch) {
      passed = parseInt(pwMatch[1], 10);
      failed = pwFailed ? parseInt(pwFailed[1], 10) : 0;
    }

    // Check for error exit code as fallback
    if (passed === 0 && failed === 0 && output.includes('Error')) {
      failed = 1;
    }

    return { passed, failed, total: passed + failed };
  }

  /**
   * Extract detailed failure information from test output.
   */
  private extractFailureDetails(output: string): TestFailure[] {
    const failures: TestFailure[] = [];

    // Pattern 1: Vitest/Jest failure format
    const failPattern1 = /(?:FAIL|✕)\s+(.+?)\n([\s\S]*?)(?=(?:FAIL|✕|✓|PASS|Tests|Test Suites|$))/g;
    let match1;
    while ((match1 = failPattern1.exec(output)) !== null) {
      const testName = match1[1].trim();
      const errorBlock = match1[2].trim();
      const errorMatch = errorBlock.match(/(?:Error|Expected|Received|assertion):?\s*([\s\S]{10,500})/);
      const stackMatch = errorBlock.match(/(at\s+[\s\S]{10,300})/);

      failures.push({
        testName,
        error: errorMatch ? errorMatch[1].trim().substring(0, 500) : errorBlock.substring(0, 300),
        stackTrace: stackMatch ? stackMatch[1].trim() : undefined,
      });
    }

    // Pattern 2: Simple "X) testname" format
    if (failures.length === 0) {
      const failPattern2 = /\d+\)\s+(.+?)\n([\s\S]*?)(?=\d+\)|\n\n|\n[A-Z])/g;
      let match2;
      while ((match2 = failPattern2.exec(output)) !== null) {
        failures.push({
          testName: match2[1].trim(),
          error: match2[2].trim().substring(0, 500),
        });
      }
    }

    // Pattern 3: "testname ... FAILED" format
    if (failures.length === 0) {
      const failPattern3 = /(.+?)\s+\.{3,}\s*(?:FAILED|ERROR)\n([\s\S]*?)(?=\n\S|\n$|$)/g;
      let match3;
      while ((match3 = failPattern3.exec(output)) !== null) {
        failures.push({
          testName: match3[1].trim(),
          error: match3[2].trim().substring(0, 500),
        });
      }
    }

    // Deduplicate by test name
    const seen = new Set<string>();
    return failures.filter(f => {
      if (seen.has(f.testName)) return false;
      seen.add(f.testName);
      return true;
    });
  }

  // ─── Frontend Detection ────────────────────────────────────────────────

  /**
   * Detect if the project is a frontend application.
   */
  private async detectFrontendProject(): Promise<boolean> {
    try {
      const packageJson = await this.fs.readFile('package.json');
      const pkg = JSON.parse(packageJson);

      const hasFrontendDeps = pkg.dependencies && (
        pkg.dependencies.react ||
        pkg.dependencies.vue ||
        pkg.dependencies['@angular/core'] ||
        pkg.dependencies.svelte ||
        pkg.dependencies.next ||
        pkg.dependencies.nuxt
      );

      const hasDevScript = pkg.scripts && (pkg.scripts.dev || pkg.scripts.start);

      return !!(hasFrontendDeps && hasDevScript);
    } catch {
      return false;
    }
  }

  // ─── Test Command Resolution ───────────────────────────────────────────

  /**
   * Resolve the test command based on the configured framework.
   */
  private resolveTestCommand(): string {
    switch (this.testFramework) {
      case 'jest':
        return 'test -- --forceExit';
      case 'vitest':
        return 'test -- --run';
      case 'mocha':
        return 'test';
      default:
        return 'test';
    }
  }

  // ─── Message Bus Publishing ────────────────────────────────────────────

  /**
   * Publish a structured test result via MessageBus.
   * This ensures all consumers receive the same structured format.
   */
  private publishTestResult(result: StructuredTestResult): void {
    this.publish('test_result', '*', result, this.getActiveTaskId() ?? undefined);
    this.logger.info('Published test_result', {
      type: result.type,
      passed: result.passedTests,
      failed: result.failedTests,
      total: result.totalTests,
    });
  }

  // ─── Helpers ───────────────────────────────────────────────────────────

  /**
   * Sleep for the given number of milliseconds.
   */
  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /**
   * Validate code against a requirement string.
   * Returns structured validation result.
   */
  async validateAgainstRequirement(
    codeFiles: string[],
    requirement: string,
  ): Promise<{ valid: boolean; issues: string[] }> {
    const prompt = `Validate if the following code meets the requirement.

## Requirement
${requirement}

## Code Files
${codeFiles.map(f => `- ${f}`).join('\n')}

Analyze:
1. Does the code implement all required features?
2. Are there any missing functionalities?
3. Are there any bugs or issues?

Respond in JSON format:
{
  "valid": boolean,
  "issues": ["issue description"]
}`;

    try {
      return await this.llm.completeStructured<{ valid: boolean; issues: string[] }>(prompt, {
        valid: 'boolean',
        issues: ['string'],
      });
    } catch {
      return { valid: false, issues: ['Validation analysis failed'] };
    }
  }
}
